std = 'lua51'

quiet = 1 -- suppress report output for files without warnings

unused_secondaries = false -- e.g. local name, _, itemLevel = GetItemInfo(...)

-- see https://luacheck.readthedocs.io/en/stable/warnings.html#list-of-warnings
-- and https://luacheck.readthedocs.io/en/stable/cli.html#patterns
exclude_files = {
    '.claude/**',
    'core/development.lua', -- dead stub, removed in rebuild item 10
    'docs/**',
    'libs/**', -- submodules (oUF is read-only)
    'modules/miscellaneous/dispels/**', -- submodule
    'modules/miscellaneous/interrupts/**', -- submodule
    'modules/miscellaneous/screenshots/**', -- submodule
}

ignore = {
    '211/[ECALP]', -- unused engine locals (local E, C, A, L = ...)
    '212', -- unused argument (callback signatures)
    '213', -- unused loop variable
    '431', -- shadowing an upvalue
    '432/self', -- shadowing upvalue argument self (nested methods)
    '611', -- line contains only whitespace
    '612', -- line contains trailing whitespace
    '614', -- trailing whitespace in comment
    '631', -- line is too long
}

-- globals Tainted is allowed to set or mutate
globals = {
    -- saved variables
    'TaintedChatHistory',
    'TaintedDatabase',

    -- slash commands
    'SLASH_RELOADUI1',
    'SLASH_TAINTED1',
    'SlashCmdList',

    -- Blizzard overrides
    'EventTrace',
    'ItemRefTooltip',
    'Minimap',
}

-- oUF tag environment
files['modules/unitframes/tags.lua'] = {
    read_globals = { '_TAGS' },
}

read_globals = {
    string = {fields = {'join', 'split', 'trim'}},
    table = {fields = {'wipe'}},

    -- Lua aliases provided by WoW
    'ceil',
    'date',
    'format',
    'min',
    'time',

    -- namespaces
    'C_AddOns',
    'C_ActionBar',
    'C_ArtifactUI',
    'C_AzeriteItem',
    'C_Bank',
    'C_BattleNet',
    'C_ChallengeMode',
    'C_Container',
    'C_CovenantSanctumUI',
    'C_CurrencyInfo',
    'C_CurveUtil',
    'C_CVar',
    'C_DateAndTime',
    'C_FriendList',
    'C_GossipInfo',
    'C_Item',
    'C_MajorFactions',
    'C_Map',
    'C_MerchantFrame',
    'C_MythicPlus',
    'C_PaperDollInfo',
    'C_PartyInfo',
    'C_PetBattles',
    'C_PetJournal',
    'C_PlayerInfo',
    'C_PvP',
    'C_Reputation',
    'C_Secrets',
    'C_SpecializationInfo',
    'C_Spell',
    'C_SpellBook',
    'C_StringUtil',
    'C_Timer',
    'C_UnitAuras',
    'C_VoiceChat',
    'C_WeeklyRewards',

    -- constants and global strings
    'ANIMA_DIVERSION_CURRENCY_TOOLTIP_TITLE',
    'ARTIFACT_POWER_BAR',
    'AZERITE_POWER_TOOLTIP_BODY',
    'BINDING_NAME_VEHICLEEXIT',
    'COVENANT_SANCTUM_TAB_RENOWN',
    'DEFAULT_CHAT_FRAME',
    'ERR_NOT_IN_COMBAT',
    'FRIENDS',
    'GENERAL_CHAT_DOCK',
    'HIGHLIGHT_FONT_COLOR',
    'ISLANDS_QUEUE_WEEKLY_QUEST_PROGRESS',
    'KEYRING_CONTAINER',
    'LE_BATTLE_PET_ALLY',
    'LE_UNIT_STAT_SPIRIT',
    'LEVEL',
    'LOCALIZED_CLASS_NAMES_MALE',
    'MAINMENUBAR_PROTOCOLS_LABEL',
    'MAJOR_FACTION_RENOWN_LEVEL_TOAST',
    'MOUSE_LABEL',
    'NORMAL_FONT_COLOR',
    'NUM_BANKGENERIC_SLOTS',
    'PET',
    'PLAYER',
    'PVP_HONOR_PRESTIGE_AVAILABLE',
    'PVP_HONOR_XP_BAR_CANNOT_PRESTIGE_HERE',
    'SELECTED_CHAT_FRAME',
    'SOUNDKIT',
    'TAXI_CANCEL',
    'UNKNOWN',
    'WORLD_RAID_MARKER_ORDER',
    'WOW_PROJECT_BURNING_CRUSADE_CLASSIC',
    'WOW_PROJECT_CAMELOT',
    'WOW_PROJECT_CATACLYSM_CLASSIC',
    'WOW_PROJECT_CLASSIC',
    'WOW_PROJECT_ID',
    'WOW_PROJECT_MAINLINE',
    'WOW_PROJECT_MISTS_CLASSIC',
    'WOW_PROJECT_WOWLABS',
    'WOW_PROJECT_WRATH_CLASSIC',
    'XP',

    -- API and FrameXML
    'ActionButton_ShowGrid',
    'AnchorUtil',
    'ArtifactBarGetNumArtifactTraitsPurchasableFromXP',
    'AuraContainerItemEnchantmentSlot',
    'AuraContainerSortDirection',
    'AuraContainerSortMethod',
    'AzeriteUtil',
    'BagsBar',
    'BankFrame',
    'BlizzardBags',
    'BNGetNumFriends',
    'BNToastFrame',
    'ChangeChatColor',
    'ChatEdit_ActivateChat',
    'ChatEdit_ChooseBoxForSend',
    'ChatEdit_DeactivateChat',
    'ChatFrame_AddMessageEventFilter',
    'ChatFrame_AddMessageGroup',
    'ChatFrame_RemoveAllChannels',
    'ChatFrame_RemoveAllMessageGroups',
    'ChatFrame_SetChannelEnabled',
    'ChatTypeInfo',
    'CloseAllWindows',
    'CloseMenus',
    'CombatLogGetCurrentEventInfo',
    'CompactRaidFrameManager_SetSetting',
    'CooldownFrame_Set',
    'CreateColor',
    'CreateFrame',
    'DoReadyCheck',
    'Enum',
    'EnumerateFrames',
    'EnumerateServerChannels',
    'FCF_DockFrame',
    'FCF_OpenNewWindow',
    'FCF_ResetChatWindows',
    'FCF_RestorePositionAndDimensions',
    'FCF_SavePositionAndDimensions',
    'FCF_SelectDockFrame',
    'FCF_SetChatWindowFontSize',
    'FCF_SetLocked',
    'FCF_SetTabPosition',
    'FCF_SetWindowName',
    'FCF_UnDockFrame',
    'FCFDock_GetChatFrames',
    'GameTime_GetFormattedTime',
    'GameTimeFrame_OnClick',
    'GameTooltip_SetDefaultAnchor',
    'GameTooltip',
    'GetActionBarToggles',
    'GetBuildInfo',
    'GetCurrentCombatTextEventInfo',
    'GetCVar',
    'GetCVarBool',
    'geterrorhandler',
    'GetFrameHandleFrame',
    'GetGuildRosterInfo',
    'GetInventoryItemTexture',
    'GetItemInfo',
    'GetKeyRingSize',
    'GetLocale',
    'GetManaRegen',
    'GetMinimapZoneText',
    'GetNumGroupMembers',
    'GetOverrideBarIndex',
    'GetPhysicalScreenSize',
    'GetQuestGreenRange',
    'GetRealmName',
    'GetScreenWidth',
    'GetSpecialization',
    'GetSpecializationRole',
    'GetSpellBookItemInfo',
    'GetTempShapeshiftBarIndex',
    'GetTime',
    'GetTotemDuration',
    'GetVehicleBarIndex',
    'GetVersatilityBonus',
    'GetWeaponEnchantInfo',
    'HasExtraActionBar',
    'HideUIPanel',
    'hooksecurefunc',
    'InCombatLockdown',
    'InitiateRolePoll',
    'IsAltKeyDown',
    'IsControlKeyDown',
    'issecretvalue',
    'IsShiftKeyDown',
    'IsSpellKnown',
    'Item',
    'LibStub',
    'MainMenuMicroButton_SetNormal',
    'MenuUtil',
    'Minimap_OnClick',
    'Minimap_Update',
    'MiniMapInstanceDifficulty',
    'MiniMapTrackingDropDown',
    'MinimapZoneText',
    'Mixin',
    'MouseIsOver',
    'PaperDollFrame_UpdateStats',
    'PartyFrame',
    'PetBattlePrimaryAbilityTooltip',
    'PlayerSpellsUtil',
    'PlaySound',
    'RegisterAttributeDriver',
    'RegisterStateDriver',
    'SecureButton_GetModifiedUnit',
    'securecall',
    'SecureHandlerSetFrameRef',
    'SetActionBarToggles',
    'SetCVar',
    'SetEveryoneIsAssistant',
    'Settings',
    'ShowUIPanel',
    'SpellBook_GetSpellBookSlot',
    'SpellBookFrame',
    'StanceBar',
    'Stopwatch_Clear',
    'Stopwatch_Pause',
    'Stopwatch_Play',
    'Stopwatch_StartCountdown',
    'Stopwatch_Toggle',
    'StopwatchFrame',
    'ToggleAllBags',
    'ToggleChannelFrame',
    'ToggleCharacter',
    'ToggleDropDownMenu',
    'ToggleFriendsFrame',
    'ToggleGuildFrame',
    'ToggleTalentFrame',
    'ToggleWorldMap',
    'TooltipDataProcessor',
    'UIDropDownMenu_AddButton',
    'UIDropDownMenu_Initialize',
    'UIFrameFadeIn',
    'UIFrameFadeOut',
    'UIFrameFadeRemoveFrame',
    'UIParent',
    'UIWidgetTemplateStatusBarMixin',
    'UnitAffectingCombat',
    'UnitArmor',
    'UnitBattlePetLevel',
    'UnitBattlePetType',
    'UnitCanAssist',
    'UnitCanAttack',
    'UnitChannelInfo',
    'UnitClass',
    'UnitClassBase',
    'UnitClassification',
    'UnitCreatureType',
    'UnitFactionGroup',
    'UnitFrame_OnLeave',
    'UnitGroupRolesAssigned',
    'UnitGUID',
    'UnitInPartyIsAI',
    'UnitIsDead',
    'UnitIsFriend',
    'UnitIsGhost',
    'UnitIsUnit',
    'UnitLevel',
    'UnitName',
    'UnitPower',
    'UnitPowerMax',
    'UnitPowerType',
    'UnitQuestTrivialLevelRange',
    'UnitReaction',
    'UnitXP',
    'UnregisterStateDriver',
}
